### ISSUE TITLE
corrupted styles.xml when downloaded by myst

### ISSUE THREAD

**Issue by spisakt** [myst-templates/docx_default#1]
Repeating the Myst tutorial, I get the following error when trying to convert my md file to docx:

```
> myst build 01-paper.md --docx

Error: Unmatched closing tag: w:styles
Line: 0
Column: 36089
Char: >

```

My md file contains this in the header:
```
exports:
  - format: pdf
    template: arxiv_nips
    output: exports/manuscript.pdf
  - format: docx
    output: exports/manuscript.docx
```

After searching the source code, I found out that the problem is with the file _build/templates/docx/myst/default

I can fix the problem by manually downloading and unzipping the template:
```
wget https://github.com/myst-templates/docx_default/archive/refs/heads/main.zip
unzip main.zip -d _build/templates/docx/myst/default     # replace all if asked
cp _build/templates/docx/myst/default/docx_default-main/styles.xml _build/templates/docx/myst/default/styles.xml
```
The conversion works afterwards:
`> myst build 01-paper.md --docx`

I am experiencing the problem on multiple computers as well as in GitHub Actions.
Does anyone else experience this issue?
What am I doing wrong?
